

document.writeln("<!--top start-->");
document.writeln("<div class=\"top\">");
document.writeln("    <div class=\"top-w\">");
document.writeln("        <!--顶部左测logo-->");
document.writeln("        <div class=\"top-left\">");
document.writeln("            <a href=\"http://game.163.com/\" target=\"_blank\" class=\"top-logo\">网易游戏</a>");
document.writeln("        </div>");
document.writeln("        <!--顶部中间的img广告-->");
document.writeln("        <div class=\"top-middle\" id=\"top_middle_zn\">");
document.writeln("            <div class=\"\">");
document.writeln("                <img src=\"images/profession/hh-news.jpg\" alt=\"\">");
document.writeln("            </div>");
document.writeln("            <!--鼠标悬停显示的大广告-->");
document.writeln("            <div class=\"top-middle-bottom\" style=\"margin-left: -135px;\">");
document.writeln("                <a href=\"#\" target=\"_blank\">");
document.writeln("                    <img src=\"images/profession/hh-news-big.jpg\" alt=\"\">");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <!--顶部右侧ul-->");
document.writeln("        <div class=\"top-right\">");
document.writeln("            <!--注册登录-->");
document.writeln("            <ul>");
document.writeln("                <li><a href=\"login.html\" target=\"_blank\">注册账号</a></li>");
document.writeln("                <li><a href=\"payGame.html\" target=\"_blank\">购卡充值</a></li>");
document.writeln("            </ul>");
document.writeln("            <!--游戏全目录-->");
document.writeln("            <div class=\"catalogue\" id=\"cataloguegame\">");
document.writeln("                    <span>");
document.writeln("                        网易游戏全目录");
document.writeln("                        <!--三角-->");
document.writeln("                        <i class=\"cataloguei\">");
document.writeln("                            <s class=\"catalogues\"></s>");
document.writeln("                        </i>");
document.writeln("                    </span>");
document.writeln("                <!--鼠标悬停显示目录大盒子-->");
document.writeln("                <div class=\"catalogue-box\" id=\"cataloguegame-box\">");
document.writeln("                    <!--移动端-->");
document.writeln("                    <div class=\"pcgame\">");
document.writeln("                        <div class=\"pcgame-top\">");
document.writeln("                            客户端游戏");
document.writeln("                        </div>");
document.writeln("                        <div class=\"pcgame-bottom\" id=\"pcBo\">");
document.writeln("                            <p>角色扮演</p>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <!--手机端-->");
document.writeln("                    <div class=\"phonegame\">");
document.writeln("                        <div class=\"phonegame-top\">");
document.writeln("                            手机游戏");
document.writeln("                        </div>");
document.writeln("                        <div class=\"phonegame-left\">");
document.writeln("                            <div class=\"phonegame-hot\" id=\"phoneBo\">");
document.writeln("                                <p>热门推荐</p>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"phonegame-newone\" id=\"po\">");
document.writeln("                                <p>新品推荐</p>");
document.writeln("                            </div>");
document.writeln("                            <div class=\"phonegame-newtwo\" id=\"potwo\">");
document.writeln("");
document.writeln("                            </div>");
document.writeln("                            <div class=\"phonegame-newthree\" id=\"pothree\">");
document.writeln("");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"more-game\">");
document.writeln("                            <a href=\"http://game.163.com/\" target=\"_blank\">更多热门手游</a>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"phonegame-right\">");
document.writeln("");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                    <!--游戏辅助-->");
document.writeln("                    <div class=\"assistgame\">");
document.writeln("                        <div class=\"assistgame-top\">");
document.writeln("                            游戏辅助");
document.writeln("                        </div>");
document.writeln("                        <div class=\"assistgame-bottom\" id=\"assbottom\">");
document.writeln("");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <!--垂直无缝链接-->");
document.writeln("            <div class=\"getgift\" id=\"giftdiv\">");
document.writeln("                <div id=\"lunbo\">");
document.writeln("                    <a href=\"http://game.163.com/\" target=\"_blank\">领取礼物</a>");
document.writeln("                    <a href=\"http://www.kaola.com/activity/detail/11835.shtml?tag=7cc46fc8c91a33ec9");
document.writeln("                          aa62298347b4ede&__da_MmVZMh_zPJ3p1rAsE\" target=\"_blank\">游戏充值9.8折</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!--top end-->");